import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const owner = 'palmier-io';
const repo = 'palmier-pro';
const branch = 'main';
const apiRoot = `https://api.github.com/repos/${owner}/${repo}`;
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const snapshotPath = path.join(root, 'docs', 'UPSTREAM_SNAPSHOT.md');
const args = new Set(process.argv.slice(2));

const headers = {
  Accept: 'application/vnd.github+json',
  'User-Agent': 'palmier-pro-windows-upstream-audit',
  'X-GitHub-Api-Version': '2022-11-28',
};

function githubToken() {
  const environmentToken = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  if (environmentToken) return environmentToken;

  try {
    return execFileSync('gh', ['auth', 'token'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return '';
  }
}

const token = githubToken();
if (token) {
  headers.Authorization = `Bearer ${token}`;
}

async function github(pathname) {
  const response = await fetch(`${apiRoot}${pathname}`, { headers });
  if (!response.ok) {
    throw new Error(`GitHub API ${response.status}: ${await response.text()}`);
  }
  return response.json();
}

async function allPages(pathname) {
  const separator = pathname.includes('?') ? '&' : '?';
  const results = [];
  for (let page = 1; ; page += 1) {
    const batch = await github(`${pathname}${separator}per_page=100&page=${page}`);
    results.push(...batch);
    if (batch.length < 100) return results;
  }
}

function escapeCell(value) {
  return String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function issueRow(issue) {
  const labels = issue.labels.map((label) => label.name).join(', ') || '-';
  return `| [#${issue.number}](${issue.html_url}) | ${escapeCell(issue.title)} | ${escapeCell(labels)} | ${issue.updated_at.slice(0, 10)} |`;
}

function pullRow(pull) {
  return `| [#${pull.number}](${pull.html_url}) | ${escapeCell(pull.title)} | ${pull.merged_at.slice(0, 10)} |`;
}

async function collect() {
  const [commit, issueRecords, pullRecords] = await Promise.all([
    github(`/commits/${branch}`),
    allPages('/issues?state=open&sort=updated&direction=desc'),
    allPages('/pulls?state=closed&sort=updated&direction=desc'),
  ]);

  return {
    commit,
    issues: issueRecords.filter((issue) => !issue.pull_request),
    pulls: pullRecords.filter((pull) => pull.merged_at).slice(0, 100),
  };
}

function renderSnapshot({ commit, issues, pulls }) {
  const generatedAt = new Date().toISOString();
  return `# Upstream Snapshot

<!-- upstream-sha: ${commit.sha} -->

Generated by \`npm run upstream:audit:write\` at ${generatedAt}.
Do not curate this file manually; record Windows dispositions in
\`docs/UPSTREAM_PARITY.md\`.

## Baseline

- Repository: [${owner}/${repo}](https://github.com/${owner}/${repo})
- Branch: \`${branch}\`
- Commit: [\`${commit.sha}\`](${commit.html_url})
- Commit date: ${commit.commit.committer.date}
- Commit title: ${commit.commit.message.split('\n')[0]}
- Open issues captured: ${issues.length}
- Recent merged pull requests captured: ${pulls.length}

## Open Issues

| Issue | Title | Labels | Updated |
|---|---|---|---|
${issues.map(issueRow).join('\n')}

## Recent Merged Pull Requests

| Pull request | Title | Merged |
|---|---|---|
${pulls.map(pullRow).join('\n')}
`;
}

async function recordedSha() {
  try {
    const snapshot = await readFile(snapshotPath, 'utf8');
    return snapshot.match(/<!-- upstream-sha: ([0-9a-f]{40}) -->/)?.[1] ?? null;
  } catch {
    return null;
  }
}

const data = await collect();
const currentSha = data.commit.sha;
const baselineSha = await recordedSha();
const isCurrent = baselineSha === currentSha;

console.log(`Upstream ${owner}/${repo}@${branch}: ${currentSha}`);
console.log(`Open issues: ${data.issues.length}`);
console.log(`Recent merged PRs captured: ${data.pulls.length}`);
console.log(`Tracked snapshot: ${baselineSha ?? 'missing'} (${isCurrent ? 'current' : 'stale'})`);

if (args.has('--write')) {
  await mkdir(path.dirname(snapshotPath), { recursive: true });
  await writeFile(snapshotPath, renderSnapshot(data), 'utf8');
  console.log(`Updated ${path.relative(root, snapshotPath)}`);
}

if (args.has('--check') && !isCurrent) {
  console.error('Upstream moved. Run npm run upstream:audit:write and review the parity ledger.');
  process.exitCode = 1;
}
